### ISSUE TITLE
Rust agent fails main Keylime CI when getting pub keys or identity quote

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#441]
All other 128 tests in [`run_local.sh`](https://github.com/keylime/keylime/blob/master/.ci/run_local.sh) pass with the Rust agent.

Output for `pubkey_get`:
```
Error in test.test_restful.TestRestful.test_071_agent_keys_pubkey_get
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8b6ed0ce50>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=9002): Max retries exceeded with url: /v2.0/keys/pubkey (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b6ed0ce50>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

  File "/usr/lib64/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib64/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/root/keylime/test/test_restful.py", line 946, in test_071_agent_keys_pubkey_get
    self.test_020_agent_keys_pubkey_get()
  File "/root/keylime/test/test_restful.py", line 535, in test_020_agent_keys_pubkey_get
    response = test_020_agent_keys_pubkey_get.get(
  File "/root/keylime/build/lib/keylime/requests_client.py", line 46, in get
    return self.session.get(self.base_url + url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=9002): Max retries exceeded with url: /v2.0/keys/pubkey (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b6ed0ce50>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Output for `quotes_identity_get`:
```
Error in test.test_restful.TestRestful.test_073_agent_quotes_identity_get
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8b6ed151c0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=9002): Max retries exceeded with url: /v2.0/quotes/identity?nonce=nEr2J1TbgmDcijpvY9Ba (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b6ed151c0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

  File "/usr/lib64/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib64/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/root/keylime/test/test_restful.py", line 956, in test_073_agent_quotes_identity_get
    self.test_022_agent_quotes_identity_get()
  File "/root/keylime/test/test_restful.py", line 567, in test_022_agent_quotes_identity_get
    response = test_022_agent_quotes_identity_get.get(
  File "/root/keylime/build/lib/keylime/requests_client.py", line 46, in get
    return self.session.get(self.base_url + url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=9002): Max retries exceeded with url: /v2.0/quotes/identity?nonce=nEr2J1TbgmDcijpvY9Ba (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b6ed151c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by lkatalin** [comment]
Actually, we've also got
```
2022-08-25 12:58:51.146 - keylime.cloudagent - INFO - TERM Signal received, shutting down...
2022-08-25 12:58:51.146 - keylime.cloudagent - INFO - Stopping revocation listener...
Cloud Agent Thread
 WARN  keylime_agent > IMA measurement list not available: /sys/kernel/security/ima/ascii_runtime_measurements
 WARN  keylime_agent > Measured boot measurement list not available: /sys/kernel/security/tpm0/binary_bios_measurements
 ERROR keylime_agent::common > Could not load keylime config file: /etc/keylime-agent.conf due to error: No such file or directory (os error 2)
Error: Ini(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }))

```

**Comment by ansasaki** [comment]
This is fixed by:

- https://github.com/keylime/keylime/pull/1103
- #448
- #432

**Comment by lkatalin** [comment]
I am still getting failures on test_restful.py tests 71, 72, 73, and 76. It appears to happen because the agent is not able to mount tmpfs:

```
2022-09-19 15:38:08.533 - keylime.cloudagent - INFO - TERM Signal received, shutting down...
2022-09-19 15:38:08.533 - keylime.cloudagent - INFO - Stopping revocation listener...
...

INFO  keylime_agent::secure_mount > Mounting secure storage location "/var/lib/keylime/secure" on tmpfs.
Error: SecureMount("unable to mount tmpfs with secure dir: exit status code exit status: 32")
```

After this point, the tests start failing and the registrar receives a 404 (because the agent has stopped). The error occurs [here](https://github.com/keylime/rust-keylime/blob/df988fc6d7742d7f9d8d0f80a46baf0ea463035c/src/secure_mount.rs#L148).

This seems to happen because the `MOUNT_SECURE` flag [is set](https://github.com/keylime/rust-keylime/blob/master/src/common.rs#L69) since the Rust agent does not detect that it is in a testing environment. I will see if I can change this behavior.

**Comment by ansasaki** [comment]
This is probably caused by https://github.com/keylime/rust-keylime/issues/360 which was not implemented.

The rust agent does not read the `KEYLIME_TEST` environment variable and does not change the behavior.

**Comment by lkatalin** [comment]
I could add another conditional to check for `KEYLIME_TEST` under `common.rs` when it is setting the `MOUNT_SECURE` flag, what do you think?

**Comment by lkatalin** [comment]
Hm, I was trying to make it compatible with the way the Keylime CI works, but I did not consider changing things on the Python side in [`run_tests.sh`](https://github.com/keylime/keylime/blob/master/test/run_tests.sh#L147) or [`run_local.sh`](https://github.com/keylime/keylime/blob/master/.ci/run_local.sh#L19). Instead of running simply `make` and `make install`, the Python CI in `run_tests.sh` could specify the testing cfg when building the Rust agent. It may involve updating the [makefile](https://github.com/keylime/rust-keylime/blob/master/GNUmakefile#L26) also. I can have a look if this sounds better.
